apiVersion: v2
name: serverservice-devel
description: A helm chart for a server service development instance.
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
- name: nats
  version: 0.18.0
  repository: https://nats-io.github.io/k8s/helm/charts/
- name: chaos-mesh
  repository: https://charts.chaos-mesh.org
  version: 2.5.1
