---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conditionorc-api-config
  namespace: default
data:
  config.yaml: |
    log_level: debug
    app_kind: server
    listen_address: localhost:9001
    store_kind: serverservice
    serverservice_options:
      endpoint: http://serverservice:8000
      disable_oauth: true
      facility_code: dc13

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conditionorc-config
  namespace: default
data:
  config.yaml: |
    log_level: debug
    app_kind: orchestrator
    listen_address: localhost:9002
    store_kind: serverservice
    serverservice_options:
      endpoint: http://serverservice:8000
      disable_oauth: true
      facility_code: dc13
    events_broker_kind: nats
    nats_options:
      url: nats://nats:4222
      app_name: conditionorc
      publisher_subject_prefix: com.hollow.sh.controllers.commands
      stream_urn_ns: hollow-controllers
      subscribe_subjects:
        - com.hollow.sh.serverservice.events.>
      connect_timeout: 500ms
      stream_user: conditionorc
      stream_pass: password
      #creds_file:
      stream:
        name: controllers
        subjects:
          - com.hollow.sh.controllers.commands.>
          - com.hollow.sh.controllers.responses.>
        acknowledgements: true
        duplicate_window: 5m
        retention: workQueue
      consumer:
        name: conditionorc
        ack_wait: 5m
        max_ack_pending: 10
        subscribe_subjects:
          - com.hollow.sh.controllers.responses.>
